# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4bead78e912b20b091bdc8e139649c27a0a8e2f7003d9861154449cc58da9150ad4fc8170f7deb8ba03e4cc5f36a9e9743d3937f9e3228111a23b043c8d24562

test:
  secret_key_base: 3f35d10e29ab7b4beece493745a095927856812cc45caee8cc9f80e850ba54fbc249ac3030ff665436e400bae05e808692d34eabbc78125a3d78f037ea265e6f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
